"""empty message

Revision ID: d112b875d734
Revises: 
Create Date: 2019-04-18 16:49:53.598250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd112b875d734'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_years_record', sa.Column('city', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_years_record', 'city')
    # ### end Alembic commands ###
